import Header from '@/components/Header'
import './globals.css'
import 'swiper/css';
import 'swiper/css/navigation';
import { Montserrat } from 'next/font/google'
import Footer from '@/components/Footer';

const monstserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type props = {
  children: React.ReactNode
}
export default function RootLayout({ children, }: props) {
  return (
    <html lang="en">
      <body className={monstserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
